top_srcdir   = /run/media/master/data/OneDrive/mei/internship/tools/httpd-2.2.11
top_builddir = /run/media/master/data/OneDrive/mei/internship/tools/httpd-2.2.11
srcdir       = /run/media/master/data/OneDrive/mei/internship/tools/httpd-2.2.11/server/mpm
builddir     = /run/media/master/data/OneDrive/mei/internship/tools/httpd-2.2.11/server/mpm
VPATH        = /run/media/master/data/OneDrive/mei/internship/tools/httpd-2.2.11/server/mpm

SUBDIRS = $(MPM_SUBDIR_NAME)

include $(top_builddir)/build/rules.mk
