top_srcdir   = /run/media/master/data/OneDrive/mei/internship/tools/httpd-2.2.11
top_builddir = /run/media/master/data/OneDrive/mei/internship/tools/httpd-2.2.11
srcdir       = /run/media/master/data/OneDrive/mei/internship/tools/httpd-2.2.11/modules/filters
builddir     = /run/media/master/data/OneDrive/mei/internship/tools/httpd-2.2.11/modules/filters
VPATH        = /run/media/master/data/OneDrive/mei/internship/tools/httpd-2.2.11/modules/filters

include $(top_srcdir)/build/special.mk

