top_srcdir   = /run/media/master/data/OneDrive/mei/internship/tools/httpd-2.2.11
top_builddir = /run/media/master/data/OneDrive/mei/internship/tools/httpd-2.2.11
srcdir       = /run/media/master/data/OneDrive/mei/internship/tools/httpd-2.2.11/server/mpm/prefork
builddir     = /run/media/master/data/OneDrive/mei/internship/tools/httpd-2.2.11/server/mpm/prefork
VPATH        = /run/media/master/data/OneDrive/mei/internship/tools/httpd-2.2.11/server/mpm/prefork

LTLIBRARY_NAME    = libprefork.la
LTLIBRARY_SOURCES = prefork.c

include $(top_srcdir)/build/ltlib.mk
