top_srcdir   = /run/media/master/data/OneDrive/mei/internship/tools/httpd-2.2.11
top_builddir = /run/media/master/data/OneDrive/mei/internship/tools/httpd-2.2.11
srcdir       = /run/media/master/data/OneDrive/mei/internship/tools/httpd-2.2.11/os/unix
builddir     = /run/media/master/data/OneDrive/mei/internship/tools/httpd-2.2.11/os/unix
VPATH        = /run/media/master/data/OneDrive/mei/internship/tools/httpd-2.2.11/os/unix

LTLIBRARY_NAME    = libos.la
LTLIBRARY_SOURCES = unixd.c

include $(top_srcdir)/build/ltlib.mk
