top_srcdir   = /run/media/master/data/OneDrive/mei/internship/tools/httpd-2.2.11
top_builddir = /run/media/master/data/OneDrive/mei/internship/tools/httpd-2.2.11
srcdir       = /run/media/master/data/OneDrive/mei/internship/tools/httpd-2.2.11/modules
builddir     = /run/media/master/data/OneDrive/mei/internship/tools/httpd-2.2.11/modules
VPATH        = /run/media/master/data/OneDrive/mei/internship/tools/httpd-2.2.11/modules

SUBDIRS = $(MODULE_DIRS)
CLEAN_SUBDIRS = $(MODULE_CLEANDIRS)

include $(top_builddir)/build/rules.mk

