top_srcdir   = /run/media/master/data/OneDrive/mei/internship/tools/httpd-2.2.11
top_builddir = /run/media/master/data/OneDrive/mei/internship/tools/httpd-2.2.11
srcdir       = /run/media/master/data/OneDrive/mei/internship/tools/httpd-2.2.11/modules/proxy
builddir     = /run/media/master/data/OneDrive/mei/internship/tools/httpd-2.2.11/modules/proxy
VPATH        = /run/media/master/data/OneDrive/mei/internship/tools/httpd-2.2.11/modules/proxy
# a modules Makefile has no explicit targets -- they will be defined by
# whatever modules are enabled. just grab special.mk to deal with this.
include $(top_srcdir)/build/special.mk
